AutoEnablePermission: "fly.autoenable"
UsePermission: "fly.use"
FlyEnabled: "&aEnabled fly"
FlyDisabled: "&cDisabled fly"
NoPermission: "&cYou dont have permission to do that!"
WhitelistWorld: "world"
BypassWhitelistWorldPermission: "fly.bypass"
OnlyPlayer: "Only player."
