name: PlayerFly
version: 1.1
main: catmoe.fallencrystal.playerfly.PlayerFly
api-version: "1.8"
authors: [FallenCrystal_]
description: idk
website: miaomoe.net
commands:
 fly:
   description: Just toggle fly
   usage: /<command>